name: Tests

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

jobs:

  # runs all of the steps inside the specified container rather than on the VM host.
  # Because of this the network configuration changes from host based network to a container network.
  test:
    runs-on: ubuntu-20.04

    container:
      image: python:3.11-buster

    steps:
      # This Docker file changes sets USER to circleci instead of using the default user, so we need to update file permissions for this image to work on GH Actions.
      # See https://docs.github.com/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem

      - name: Setup file system permissions
        run: chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        shell: bash
        run: |
          apt update -y && apt upgrade -y
          export DEBIAN_FRONTEND=noninteractive
          ln -fs /usr/share/zoneinfo/Africa/Lusaka /etc/localtime
          dpkg-reconfigure --frontend noninteractive tzdata
          python -VV # Print out python version for debugging
          which python # for debugging
          pip3 install virtualenv
          virtualenv ~/venv
          source ~/venv/bin/activate
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        shell: bash
        run: |
          source ~/venv/bin/activate
          pytest
